
package Server_client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerController", targetNamespace = "http://Server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerController {


    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.WebServerTransferObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSymbols", targetNamespace = "http://Server/", className = "Server_client.GetSymbols")
    @ResponseWrapper(localName = "getSymbolsResponse", targetNamespace = "http://Server/", className = "Server_client.GetSymbolsResponse")
    public WebServerTransferObject getSymbols(
        @WebParam(name = "arg0", targetNamespace = "")
        WebServerTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.WebServerTransferObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executeSpin", targetNamespace = "http://Server/", className = "Server_client.ExecuteSpin")
    @ResponseWrapper(localName = "executeSpinResponse", targetNamespace = "http://Server/", className = "Server_client.ExecuteSpinResponse")
    public WebServerTransferObject executeSpin(
        @WebParam(name = "arg0", targetNamespace = "")
        WebServerTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.WebServerTransferObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "randomizeMathValues", targetNamespace = "http://Server/", className = "Server_client.RandomizeMathValues")
    @ResponseWrapper(localName = "randomizeMathValuesResponse", targetNamespace = "http://Server/", className = "Server_client.RandomizeMathValuesResponse")
    public WebServerTransferObject randomizeMathValues(
        @WebParam(name = "arg0", targetNamespace = "")
        WebServerTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.WebServerTransferObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createGame", targetNamespace = "http://Server/", className = "Server_client.CreateGame")
    @ResponseWrapper(localName = "createGameResponse", targetNamespace = "http://Server/", className = "Server_client.CreateGameResponse")
    public WebServerTransferObject createGame(
        @WebParam(name = "arg0", targetNamespace = "")
        WebServerTransferObject arg0);

}
