
package Server_client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerController", targetNamespace = "http://Server/", wsdlLocation = "http://localhost:8080/VideoSlotWebServer/ServerController?wsdl")
public class ServerController_Service
    extends Service
{

    private final static URL SERVERCONTROLLER_WSDL_LOCATION;
    private final static WebServiceException SERVERCONTROLLER_EXCEPTION;
    private final static QName SERVERCONTROLLER_QNAME = new QName("http://Server/", "ServerController");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/VideoSlotWebServer/ServerController?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERCONTROLLER_WSDL_LOCATION = url;
        SERVERCONTROLLER_EXCEPTION = e;
    }

    public ServerController_Service() {
        super(__getWsdlLocation(), SERVERCONTROLLER_QNAME);
    }

    public ServerController_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERCONTROLLER_QNAME, features);
    }

    public ServerController_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVERCONTROLLER_QNAME);
    }

    public ServerController_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERCONTROLLER_QNAME, features);
    }

    public ServerController_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerController_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerController
     */
    @WebEndpoint(name = "ServerControllerPort")
    public ServerController getServerControllerPort() {
        return super.getPort(new QName("http://Server/", "ServerControllerPort"), ServerController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerController
     */
    @WebEndpoint(name = "ServerControllerPort")
    public ServerController getServerControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Server/", "ServerControllerPort"), ServerController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERCONTROLLER_EXCEPTION!= null) {
            throw SERVERCONTROLLER_EXCEPTION;
        }
        return SERVERCONTROLLER_WSDL_LOCATION;
    }

}
