
package Server_client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerController", targetNamespace = "http://Server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerController {


    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.WebServerTransferObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSymbols", targetNamespace = "http://Server/", className = "Server_client.GetSymbols")
    @ResponseWrapper(localName = "getSymbolsResponse", targetNamespace = "http://Server/", className = "Server_client.GetSymbolsResponse")
    public WebServerTransferObject getSymbols(
        @WebParam(name = "arg0", targetNamespace = "")
        WebServerTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.WebServerTransferObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLinePayouts", targetNamespace = "http://Server/", className = "Server_client.GetLinePayouts")
    @ResponseWrapper(localName = "getLinePayoutsResponse", targetNamespace = "http://Server/", className = "Server_client.GetLinePayoutsResponse")
    public WebServerTransferObject getLinePayouts(
        @WebParam(name = "arg0", targetNamespace = "")
        WebServerTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.WebServerTransferObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveSPositions", targetNamespace = "http://Server/", className = "Server_client.SaveSPositions")
    @ResponseWrapper(localName = "saveSPositionsResponse", targetNamespace = "http://Server/", className = "Server_client.SaveSPositionsResponse")
    public WebServerTransferObject saveSPositions(
        @WebParam(name = "arg0", targetNamespace = "")
        WebServerTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.WebServerTransferObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPositions", targetNamespace = "http://Server/", className = "Server_client.GetPositions")
    @ResponseWrapper(localName = "getPositionsResponse", targetNamespace = "http://Server/", className = "Server_client.GetPositionsResponse")
    public WebServerTransferObject getPositions(
        @WebParam(name = "arg0", targetNamespace = "")
        WebServerTransferObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.WebServerTransferObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://Server/", className = "Server_client.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://Server/", className = "Server_client.UpdateUserResponse")
    public WebServerTransferObject updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        WebServerTransferObject arg0);

}
